# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_app(object):
    def setupUi(self, form_app):
        form_app.setObjectName("form_app")
        form_app.resize(261, 170)
        form_app.setStyleSheet("QWidget#form_app {\n"
"    background-color: white;\n"
"}")
        self.get_osk = QtWidgets.QPushButton(form_app)
        self.get_osk.setGeometry(QtCore.QRect(30, 10, 201, 23))
        self.get_osk.setStyleSheet("QPushButton#get_osk {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    border-radius: 3px;        \n"
"    font: 75 10pt \"Arial\";\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#get_osk:hover {\n"
"    border: 3px solid rgb(66, 131, 197);\n"
"}\n"
"\n"
"QPushButton#get_osk:pressed {\n"
"    border: 3px solid rgb(66, 131, 197);\n"
"    font: 75 11pt \"Arial\";\n"
"}")
        self.get_osk.setCheckable(False)
        self.get_osk.setAutoDefault(True)
        self.get_osk.setDefault(False)
        self.get_osk.setFlat(False)
        self.get_osk.setObjectName("get_osk")
        self.select_lang_rus = QtWidgets.QRadioButton(form_app)
        self.select_lang_rus.setGeometry(QtCore.QRect(30, 70, 81, 20))
        self.select_lang_rus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.select_lang_rus.setAutoFillBackground(False)
        self.select_lang_rus.setStyleSheet("QRadioButton#select_lang_rus{\n"
"    color: rgb(85, 170, 255);\n"
"    font: 75 10px \"Arial Black\";\n"
"}\n"
"\n"
"QRadioButton#select_lang_rus::indicator{\n"
"    color: red;\n"
"}\n"
"")
        self.select_lang_rus.setCheckable(True)
        self.select_lang_rus.setChecked(True)
        self.select_lang_rus.setObjectName("select_lang_rus")
        self.select_lang_eng = QtWidgets.QRadioButton(form_app)
        self.select_lang_eng.setGeometry(QtCore.QRect(140, 70, 91, 20))
        self.select_lang_eng.setStyleSheet("QRadioButton#select_lang_eng {\n"
"    color: rgb(85, 170, 255);\n"
"    font: 75 10px \"Arial Black\";\n"
"}")
        self.select_lang_eng.setObjectName("select_lang_eng")
        self.text_language = QtWidgets.QLabel(form_app)
        self.text_language.setGeometry(QtCore.QRect(40, 40, 181, 21))
        self.text_language.setStyleSheet("QLabel#text_language {\n"
"    color: black;\n"
"    font: 75 9pt \"Arial\";\n"
"}")
        self.text_language.setScaledContents(False)
        self.text_language.setAlignment(QtCore.Qt.AlignCenter)
        self.text_language.setObjectName("text_language")
        self.received_osk = QtWidgets.QTextEdit(form_app)
        self.received_osk.setGeometry(QtCore.QRect(20, 100, 221, 60))
        self.received_osk.setStyleSheet("QTextEdit#received_osk {\n"
"    border:1px solid rgb(85, 170, 255);\n"
"    border-radius: 3px;    \n"
"}")
        self.received_osk.setObjectName("received_osk")

        self.retranslateUi(form_app)
        QtCore.QMetaObject.connectSlotsByName(form_app)

    def retranslateUi(self, form_app):
        _translate = QtCore.QCoreApplication.translate
        form_app.setWindowTitle(_translate("form_app", "Form"))
        self.get_osk.setText(_translate("form_app", "Сгенерировать оскорбление"))
        self.select_lang_rus.setText(_translate("form_app", "Русский"))
        self.select_lang_eng.setText(_translate("form_app", "Английский"))
        self.text_language.setText(_translate("form_app", "Выберите язык оскорбления"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_app = QtWidgets.QWidget()
    ui = Ui_form_app()
    ui.setupUi(form_app)
    form_app.show()
    sys.exit(app.exec_())
